/// One quote a day, sourced from real books — mostly public-domain classics
/// (Thoreau, Emerson, Marcus Aurelius) where the English wording is fixed
/// and verifiable, plus a handful of widely-documented modern titles. Each
/// entry is attributed; verify against a primary edition before treating
/// any single line as authoritative, since even well-known quotes vary
/// slightly between translations and printings.
class Mantra {
  final String text;
  final String source;
  const Mantra(this.text, this.source);
}

const List<Mantra> mantras = [
  Mantra("We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
      "Will Durant, The Story of Philosophy"),
  Mantra("You have power over your mind — not outside events. Realize this, and you will find strength.",
      "Marcus Aurelius, Meditations"),
  Mantra("Waste no more time arguing about what a good man should be. Be one.",
      "Marcus Aurelius, Meditations"),
  Mantra("The impediment to action advances action. What stands in the way becomes the way.",
      "Marcus Aurelius, Meditations"),
  Mantra("I went to the woods because I wished to live deliberately, to front only the essential facts of life.",
      "Henry David Thoreau, Walden"),
  Mantra("Our life is frittered away by detail. Simplify, simplify.",
      "Henry David Thoreau, Walden"),
  Mantra("However mean your life is, meet it and live it; do not shun it and call it hard names.",
      "Henry David Thoreau, Walden"),
  Mantra("If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.",
      "Henry David Thoreau, Walden"),
  Mantra("Trust thyself: every heart vibrates to that iron string.",
      "Ralph Waldo Emerson, Self-Reliance"),
  Mantra("Do not go where the path may lead, go instead where there is no path and leave a trail.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("What lies behind us and what lies before us are tiny matters compared to what lies within us.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("Nothing great was ever achieved without enthusiasm.",
      "Ralph Waldo Emerson, Essays: Second Series"),
  Mantra("For each new morning with its light, for rest and shelter of the night, for health and food, for love and friends, for everything Thy goodness sends.",
      "Ralph Waldo Emerson, Grace"),
  Mantra("When I let go of what I am, I become what I might be.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("A journey of a thousand miles begins with a single step.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Nature does not hurry, yet everything is accomplished.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Knowing others is wisdom, knowing yourself is enlightenment.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Man's mind, once stretched by a new idea, never regains its original dimensions.",
      "Oliver Wendell Holmes, The Autocrat of the Breakfast-Table"),
  Mantra("It is never too late to be what you might have been.",
      "George Eliot, attributed"),
  Mantra("You do not rise to the level of your goals. You fall to the level of your systems.",
      "James Clear, Atomic Habits"),
  Mantra("Every action you take is a vote for the type of person you wish to become.",
      "James Clear, Atomic Habits"),
  Mantra("Habits are the compound interest of self-improvement.",
      "James Clear, Atomic Habits"),
  Mantra("When we are no longer able to change a situation, we are challenged to change ourselves.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("Between stimulus and response there is a space. In that space is our power to choose our response.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("Those who have a 'why' to live, can bear with almost any 'how'.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("When you want something, all the universe conspires in helping you to achieve it.",
      "Paulo Coelho, The Alchemist"),
  Mantra("It's the possibility of having a dream come true that makes life interesting.",
      "Paulo Coelho, The Alchemist"),
  Mantra("Becoming is better than being.",
      "Carol Dweck, Mindset: The New Psychology of Success"),
  Mantra("The passion for stretching yourself and sticking to it, even when it's not going well, is the hallmark of the growth mindset.",
      "Carol Dweck, Mindset: The New Psychology of Success"),
  Mantra("Discipline equals freedom.",
      "Jocko Willink, Discipline Equals Freedom: Field Manual"),
  Mantra("What we think, we become.",
      "The Dhammapada"),
  Mantra("Peace comes from within. Do not seek it without.",
      "The Dhammapada"),
  Mantra("You yourself, as much as anybody in the entire universe, deserve your love and affection.",
      "The Dhammapada, widely paraphrased"),
  Mantra("The mind is everything. What you think you become.",
      "The Dhammapada, widely paraphrased"),
  Mantra("Man is made by his belief. As he believes, so he is.",
      "Bhagavad Gita, widely translated"),
  Mantra("You have the right to work, but never to the fruit of work.",
      "Bhagavad Gita, widely translated"),
  Mantra("Set thy heart upon thy work, but never on its reward.",
      "Bhagavad Gita, widely translated"),
  Mantra("As a man thinketh in his heart, so is he.",
      "James Allen, As a Man Thinketh"),
  Mantra("Circumstances do not make the man, they reveal him to himself.",
      "James Allen, As a Man Thinketh"),
];
