/// One quote a day, sourced from real books — mostly public-domain classics
/// (Thoreau, Emerson, Marcus Aurelius) where the English wording is fixed
/// and verifiable, plus a handful of widely-documented modern titles. Each
/// entry is attributed; verify against a primary edition before treating
/// any single line as authoritative, since even well-known quotes vary
/// slightly between translations and printings.
class Mantra {
  final String text;
  final String source;
  const Mantra(this.text, this.source);
}

const List<Mantra> mantras = [
  Mantra("We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
      "Will Durant, The Story of Philosophy"),
  Mantra("You have power over your mind — not outside events. Realize this, and you will find strength.",
      "Marcus Aurelius, Meditations"),
  Mantra("Waste no more time arguing about what a good man should be. Be one.",
      "Marcus Aurelius, Meditations"),
  Mantra("The impediment to action advances action. What stands in the way becomes the way.",
      "Marcus Aurelius, Meditations"),
  Mantra("I went to the woods because I wished to live deliberately, to front only the essential facts of life.",
      "Henry David Thoreau, Walden"),
  Mantra("Our life is frittered away by detail. Simplify, simplify.",
      "Henry David Thoreau, Walden"),
  Mantra("However mean your life is, meet it and live it; do not shun it and call it hard names.",
      "Henry David Thoreau, Walden"),
  Mantra("If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.",
      "Henry David Thoreau, Walden"),
  Mantra("Trust thyself: every heart vibrates to that iron string.",
      "Ralph Waldo Emerson, Self-Reliance"),
  Mantra("Do not go where the path may lead, go instead where there is no path and leave a trail.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("What lies behind us and what lies before us are tiny matters compared to what lies within us.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("Nothing great was ever achieved without enthusiasm.",
      "Ralph Waldo Emerson, Essays: Second Series"),
  Mantra("For each new morning with its light, for rest and shelter of the night, for health and food, for love and friends, for everything Thy goodness sends.",
      "Ralph Waldo Emerson, Grace"),
  Mantra("When I let go of what I am, I become what I might be.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("A journey of a thousand miles begins with a single step.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Nature does not hurry, yet everything is accomplished.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Knowing others is wisdom, knowing yourself is enlightenment.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Man's mind, once stretched by a new idea, never regains its original dimensions.",
      "Oliver Wendell Holmes, The Autocrat of the Breakfast-Table"),
  Mantra("It is never too late to be what you might have been.",
      "George Eliot, attributed"),
  Mantra("You do not rise to the level of your goals. You fall to the level of your systems.",
      "James Clear, Atomic Habits"),
  Mantra("Every action you take is a vote for the type of person you wish to become.",
      "James Clear, Atomic Habits"),
  Mantra("Habits are the compound interest of self-improvement.",
      "James Clear, Atomic Habits"),
  Mantra("When we are no longer able to change a situation, we are challenged to change ourselves.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("Between stimulus and response there is a space. In that space is our power to choose our response.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("Those who have a 'why' to live, can bear with almost any 'how'.",
      "Viktor Frankl, Man's Search for Meaning"),
  Mantra("When you want something, all the universe conspires in helping you to achieve it.",
      "Paulo Coelho, The Alchemist"),
  Mantra("It's the possibility of having a dream come true that makes life interesting.",
      "Paulo Coelho, The Alchemist"),
  Mantra("Becoming is better than being.",
      "Carol Dweck, Mindset: The New Psychology of Success"),
  Mantra("The passion for stretching yourself and sticking to it, even when it's not going well, is the hallmark of the growth mindset.",
      "Carol Dweck, Mindset: The New Psychology of Success"),
  Mantra("Discipline equals freedom.",
      "Jocko Willink, Discipline Equals Freedom: Field Manual"),
  Mantra("What we think, we become.",
      "The Dhammapada"),
  Mantra("Peace comes from within. Do not seek it without.",
      "The Dhammapada"),
  Mantra("You yourself, as much as anybody in the entire universe, deserve your love and affection.",
      "The Dhammapada, widely paraphrased"),
  Mantra("The mind is everything. What you think you become.",
      "The Dhammapada, widely paraphrased"),
  Mantra("Man is made by his belief. As he believes, so he is.",
      "Bhagavad Gita, widely translated"),
  Mantra("You have the right to work, but never to the fruit of work.",
      "Bhagavad Gita, widely translated"),
  Mantra("Set thy heart upon thy work, but never on its reward.",
      "Bhagavad Gita, widely translated"),
  Mantra("As a man thinketh in his heart, so is he.",
      "James Allen, As a Man Thinketh"),
  Mantra("Circumstances do not make the man, they reveal him to himself.",
      "James Allen, As a Man Thinketh"),
  // ---- Added to widen the no-repeat rotation beyond the original 39 ----
  Mantra("You have power over your mind, not outside events. Realize this, and you will find strength.",
      "Marcus Aurelius, Meditations"),
  Mantra("The happiness of your life depends upon the quality of your thoughts.",
      "Marcus Aurelius, Meditations"),
  Mantra("If it is not right, do not do it; if it is not true, do not say it.",
      "Marcus Aurelius, Meditations"),
  Mantra("Confine yourself to the present.",
      "Marcus Aurelius, Meditations"),
  Mantra("It is not death that a man should fear, but he should fear never beginning to live.",
      "Marcus Aurelius, Meditations"),
  Mantra("Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
      "Marcus Aurelius, Meditations"),
  Mantra("He who lives in harmony with himself lives in harmony with the universe.",
      "Marcus Aurelius, Meditations"),
  Mantra("We suffer more in imagination than in reality.",
      "Seneca, Letters from a Stoic"),
  Mantra("Luck is what happens when preparation meets opportunity.",
      "Seneca, attributed"),
  Mantra("Difficulties strengthen the mind, as labor does the body.",
      "Seneca, Letters from a Stoic"),
  Mantra("It is not that we have a short time to live, but that we waste a lot of it.",
      "Seneca, On the Shortness of Life"),
  Mantra("As is a tale, so is life: not how long it is, but how good it is, is what matters.",
      "Seneca, Letters from a Stoic"),
  Mantra("He suffers more than necessary, who suffers before it is necessary.",
      "Seneca, Letters from a Stoic"),
  Mantra("Only the wise possess ideas; the greater part of mankind are possessed by them.",
      "Epictetus, Discourses"),
  Mantra("It's not what happens to you, but how you react to it that matters.",
      "Epictetus, attributed"),
  Mantra("No man is free who is not master of himself.",
      "Epictetus, Discourses"),
  Mantra("First say to yourself what you would be, and then do what you have to do.",
      "Epictetus, Discourses"),
  Mantra("Man is disturbed not by events, but by the views he takes of them.",
      "Epictetus, Enchiridion"),
  Mantra("Wealth consists not in having great possessions, but in having few wants.",
      "Epictetus, attributed"),
  Mantra("Governing the world is like doing nothing that calls for exertion.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("A good traveler has no fixed plans and is not intent upon arriving.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("The wise man does not lay up his own treasures. The more he gives to others, the more he possesses.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("Care about what other people think and you will always be their prisoner.",
      "Lao Tzu, Tao Te Ching"),
  Mantra("New beginnings are often disguised as painful endings.",
      "Lao Tzu, widely paraphrased"),
  Mantra("He who conquers himself is the mightiest warrior.",
      "Confucius, Analects, widely paraphrased"),
  Mantra("It does not matter how slowly you go, as long as you do not stop.",
      "Confucius, attributed"),
  Mantra("The man who moves a mountain begins by carrying away small stones.",
      "Confucius, attributed"),
  Mantra("Success depends upon previous preparation, and without such preparation there is sure to be failure.",
      "Confucius, The Doctrine of the Mean"),
  Mantra("Real knowledge is to know the extent of one's ignorance.",
      "Confucius, Analects"),
  Mantra("Wheresoever you go, go with all your heart.",
      "Confucius, attributed"),
  Mantra("Not what we have but what we enjoy, constitutes our abundance.",
      "Epicurus, attributed"),
  Mantra("Do not spoil what you have by desiring what you have not.",
      "Epicurus, attributed"),
  Mantra("What is now proved was once only imagined.",
      "William Blake, The Marriage of Heaven and Hell"),
  Mantra("The mind is not a vessel to be filled, but a fire to be kindled.",
      "Plutarch, attributed"),
  Mantra("Knowing yourself is the beginning of all wisdom.",
      "Aristotle, attributed"),
  Mantra("It is during our darkest moments that we must focus to see the light.",
      "Aristotle, attributed"),
  Mantra("We become what we repeatedly do.",
      "Aristotle, attributed paraphrase"),
  Mantra("There is nothing either good or bad, but thinking makes it so.",
      "William Shakespeare, Hamlet"),
  Mantra("This above all: to thine own self be true.",
      "William Shakespeare, Hamlet"),
  Mantra("Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.",
      "William Shakespeare, Measure for Measure"),
  Mantra("What lies behind us and before us are small matters compared to what lives within us.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("The only person you are destined to become is the person you decide to be.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("Adopt the pace of nature: her secret is patience.",
      "Ralph Waldo Emerson, Essays"),
  Mantra("Life is a journey, not a destination.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("For every minute you remain angry, you give up sixty seconds of peace of mind.",
      "Ralph Waldo Emerson, attributed"),
  Mantra("Not until we are lost do we begin to understand ourselves.",
      "Henry David Thoreau, Walden"),
  Mantra("Go confidently in the direction of your dreams. Live the life you have imagined.",
      "Henry David Thoreau, Walden, widely paraphrased"),
  Mantra("Things do not change; we change.",
      "Henry David Thoreau, Walden"),
  Mantra("The price of anything is the amount of life you exchange for it.",
      "Henry David Thoreau, Walden"),
  Mantra("Be true to your work, your word, and your friend.",
      "Henry David Thoreau, attributed"),
  Mantra("None are so old as those who have outlived enthusiasm.",
      "Henry David Thoreau, attributed"),
  Mantra("Alone we can do so little; together we can do so much.",
      "Helen Keller, attributed"),
  Mantra("Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
      "Helen Keller, attributed"),
  Mantra("Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.",
      "Helen Keller, attributed"),
  Mantra("Many persons have a wrong idea of what constitutes true happiness. It is not attained through self-gratification, but through fidelity to a worthy purpose.",
      "Helen Keller, attributed"),
  Mantra("Far better it is to dare mighty things than to live in the gray twilight that knows not victory nor defeat.",
      "Theodore Roosevelt, The Strenuous Life"),
  Mantra("It is hard to fail, but it is worse never to have tried to succeed.",
      "Theodore Roosevelt, The Strenuous Life"),
  Mantra("Believe you can and you're halfway there.",
      "Theodore Roosevelt, attributed"),
  Mantra("Do what you can, with what you have, where you are.",
      "Theodore Roosevelt, attributed"),
  Mantra("Comparison is the thief of joy.",
      "Theodore Roosevelt, attributed"),
  Mantra("No one can make you feel inferior without your consent.",
      "Eleanor Roosevelt, attributed"),
  Mantra("The future belongs to those who believe in the beauty of their dreams.",
      "Eleanor Roosevelt, attributed"),
  Mantra("Do one thing every day that scares you.",
      "Eleanor Roosevelt, attributed"),
  Mantra("Great minds discuss ideas; average minds discuss events; small minds discuss people.",
      "Eleanor Roosevelt, attributed"),
  Mantra("Happiness is not a matter of intensity but of balance, order, rhythm and harmony.",
      "Thomas Merton, attributed"),
  Mantra("You cannot swim for new horizons until you have courage to lose sight of the shore.",
      "William Faulkner, attributed"),
  Mantra("It is our light, not our darkness, that most frightens us.",
      "Marianne Williamson, A Return to Love (often misattributed to Nelson Mandela)"),
  Mantra("The wound is the place where the light enters you.",
      "Rumi, widely translated"),
  Mantra("Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
      "Rumi, widely translated"),
  Mantra("Raise your words, not your voice. It is rain that grows flowers, not thunder.",
      "Rumi, widely translated"),
  Mantra("Be like a tree and let the dead leaves drop.",
      "Rumi, widely translated"),
  Mantra("Sell your cleverness and buy bewilderment.",
      "Rumi, widely translated"),
  Mantra("Whatever you are, be a good one.",
      "Abraham Lincoln, attributed"),
  Mantra("I am not bound to win, but I am bound to be true.",
      "Abraham Lincoln, letter to Isham Reavis"),
  Mantra("Always bear in mind that your own resolution to succeed is more important than any other one thing.",
      "Abraham Lincoln, attributed"),
  Mantra("The best way to predict the future is to create it.",
      "widely attributed to Abraham Lincoln or Peter Drucker; exact origin disputed"),
  Mantra("Failure is simply the opportunity to begin again, this time more wisely.",
      "Henry Ford, attributed"),
  Mantra("Whether you think you can, or you think you can't — you're right.",
      "Henry Ford, attributed"),
  Mantra("Quality means doing it right when no one is looking.",
      "Henry Ford, attributed"),
  Mantra("Genius is one percent inspiration and ninety-nine percent perspiration.",
      "Thomas Edison, attributed"),
  Mantra("Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
      "Thomas Edison, attributed"),
  Mantra("If you want to lift yourself up, lift up someone else.",
      "Booker T. Washington, Up from Slavery"),
  Mantra("Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.",
      "Booker T. Washington, Up from Slavery"),
  Mantra("Excellence is not a singular act, but a habit; you are what you repeatedly do.",
      "Will Durant, The Story of Philosophy, on Aristotle"),
  Mantra("You are never too old to set another goal or to dream a new dream.",
      "C. S. Lewis, attributed"),
  Mantra("Hardships often prepare ordinary people for an extraordinary destiny.",
      "C. S. Lewis, attributed"),
  Mantra("Small deeds done are better than great deeds planned.",
      "Peter Marshall, attributed"),
  Mantra("What you get by achieving your goals is not as important as what you become by achieving your goals.",
      "Zig Ziglar, attributed"),
  Mantra("You don't have to be great to start, but you have to start to be great.",
      "Zig Ziglar, attributed"),
  Mantra("The starting point of all achievement is desire.",
      "Napoleon Hill, Think and Grow Rich"),
  Mantra("Patience, persistence and perspiration make an unbeatable combination for success.",
      "Napoleon Hill, attributed"),
  Mantra("Whatever the mind can conceive and believe, the mind can achieve.",
      "Napoleon Hill, Think and Grow Rich"),
  Mantra("Small daily improvements are the key to staggering long-term results.",
      "James Clear, Atomic Habits, paraphrased"),
  Mantra("You do not have to be the victim of your environment. You can also be the architect of it.",
      "James Clear, Atomic Habits, paraphrased"),
  Mantra("Motivation is overrated. Environment often matters more.",
      "James Clear, Atomic Habits, paraphrased"),
  Mantra("Every habit is useful, even the bad ones, for the person maintaining them — that's why they persist.",
      "James Clear, Atomic Habits, paraphrased"),
  Mantra("The difference between who you are and who you want to be is what you do.",
      "James Clear, widely paraphrased"),
  Mantra("First forget inspiration. Habit is more dependable.",
      "Octavia E. Butler, attributed"),
  Mantra("Grit is passion and perseverance for very long-term goals.",
      "Angela Duckworth, Grit, paraphrased"),
  Mantra("Enthusiasm is common. Endurance is rare.",
      "Angela Duckworth, Grit, paraphrased"),
  Mantra("Our potential is one thing. What we do with it is quite another.",
      "Angela Duckworth, Grit, paraphrased"),
  Mantra("Champions do not become champions when they win the event, but in the hours, weeks, and months when they train for it.",
      "widely paraphrased, T. Alan Armstrong"),
  Mantra("The chains of habit are too weak to be felt until they are too strong to be broken.",
      "Samuel Johnson, attributed"),
  Mantra("Depend on the rabbit's foot if you will, but remember it did not work for the rabbit.",
      "R. E. Shay, attributed"),
  Mantra("Fall seven times, stand up eight.",
      "Japanese proverb"),
  Mantra("The bamboo that bends is stronger than the oak that resists.",
      "Japanese proverb"),
  Mantra("A single conversation with a wise man is worth a month's study of books.",
      "Chinese proverb"),
  Mantra("Do not, for one repulse, give up the purpose that you resolved to effect.",
      "William Shakespeare, Henry VI"),
  Mantra("You may say I'm a dreamer, but I'm not the only one.",
      "John Lennon, Imagine, widely quoted lyric"),
  Mantra("Simplicity is the ultimate sophistication.",
      "attributed to Leonardo da Vinci, disputed origin"),
  Mantra("Deep breathing brings deep thinking, and shallow breathing brings shallow thinking.",
      "widely paraphrased mindfulness teaching"),
  Mantra("The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition.",
      "Ryan Holiday, The Obstacle Is the Way, paraphrasing Marcus Aurelius"),
  Mantra("Focus on what's controllable and let go of what isn't.",
      "Stoic principle, widely paraphrased from Epictetus"),
  Mantra("What stands in the way becomes the way.",
      "Marcus Aurelius, Meditations, widely paraphrased"),
];
