/// 120 mantras. One a day, no repeat for four months.
/// Mixed register: practical, spiritual, blunt.
const List<String> mantras = [
  "I choose one aligned action over ten scattered ones.",
  "Today asks for attention, not intensity.",
  "I don't need permission to begin again.",
  "The work I avoid is the work that moves me.",
  "Enough is a decision, not an amount.",
  "I keep my promises to myself first.",
  "Slow and finished beats fast and abandoned.",
  "What I tend to, grows.",
  "I am allowed to do this imperfectly.",
  "Nobody is coming. That's fine, I'm here.",
  "I trust the pace I'm actually moving at.",
  "The next right step is usually small.",
  "I can be tired and still be steady.",
  "Attention is the only currency I truly spend.",
  "I finish what I start, or I let it go cleanly.",
  "Discipline is just kindness with a longer memory.",
  "My mornings decide my afternoons.",
  "I meet today as it is, not as I feared.",
  "Momentum is built, not found.",
  "I put the important thing first, before the world asks.",
  "Comparison tells me nothing useful.",
  "I return to the plan without punishing myself.",
  "Rest is part of the work, not a reward for it.",
  "I do the boring thing well.",
  "One page. One walk. One honest hour.",
  "The urgent is rarely the important.",
  "I am building something only I can see yet.",
  "Consistency is a form of self-respect.",
  "I don't negotiate with the snooze button.",
  "What I practise, I become.",
  "Abundance is already moving toward me.",
  "I release the outcome and keep the effort.",
  "I am exactly where the work begins.",
  "Gratitude changes what I notice.",
  "I make space and the right things arrive.",
  "My energy goes where I choose to send it.",
  "I trust what I've set in motion.",
  "Alignment feels like ease, not force.",
  "I receive as easily as I give.",
  "Every quiet effort compounds.",
  "The life I want is built in ordinary hours.",
  "I am the kind of person who follows through.",
  "I speak about my work as if it matters, because it does.",
  "There is time for what I actually value.",
  "I let go of the version of today I imagined.",
  "My worth is not a productivity score.",
  "Clarity comes from starting, not from thinking.",
  "I take the meeting with myself seriously.",
  "Progress hides in days that feel unremarkable.",
  "I choose depth over noise.",
  "Stop deciding. Start moving.",
  "You already know the first step.",
  "Nothing improves at the level of intention.",
  "Do it badly, then do it again.",
  "Half an hour beats a perfect plan.",
  "The excuse is familiar. Ignore it.",
  "You've done harder things while less prepared.",
  "Waiting to feel ready is a decision to wait.",
  "Close the tabs. Open the file.",
  "Motivation arrives after the work, not before.",
  "Say no once, protect the whole afternoon.",
  "Small and boring is the strategy.",
  "It's not busy, it's unfocused.",
  "Finish it or delete it.",
  "The habit doesn't care how you feel.",
  "You'll be glad at nine tonight.",
  "Three things. Not thirty.",
  "Effort now, ease later.",
  "Don't confuse motion with progress.",
  "Do the first thing before you check the phone.",
  "I make decisions once, then I stop revisiting them.",
  "The plan is a tool, not a verdict.",
  "I can change direction without starting over.",
  "I protect the first hour of my day.",
  "Doing less, better, is the harder discipline.",
  "I notice when I'm avoiding, and I name it.",
  "Today I keep one promise fully.",
  "The mess is part of making anything.",
  "I choose the work that scares me slightly.",
  "Focus is a muscle and it recovers.",
  "I begin before I believe.",
  "Whatever I water is what will grow.",
  "I am not behind. There is no line.",
  "I can hold ambition and patience together.",
  "The path clears as I walk it.",
  "I invite what I'm ready to hold.",
  "Ease is allowed to be part of this.",
  "I trust the seasons of my own effort.",
  "What is mine will not pass me by.",
  "I move with intention, not urgency.",
  "I have enough time for what matters most.",
  "Stillness is where I hear the next step.",
  "I choose thoughts that make the work possible.",
  "Everything I build begins as a decision.",
  "Do the thing you'll be proud you did.",
  "One priority is a strategy. Three is a plan. Ten is a wish.",
  "Show up unimpressive. Show up anyway.",
  "The scroll is not a break. It's a leak.",
  "Track it or it didn't happen.",
  "Say the hard thing early.",
  "Protect the streak. It's carrying you.",
  "Boredom is the price of mastery.",
  "You can rest without quitting.",
  "The list isn't the work.",
  "Two minutes is enough to break the standstill.",
  "Own the mistake by lunchtime.",
  "Fewer commitments, kept better.",
  "Your future self is watching this hour.",
  "Nothing gets easier. You get steadier.",
  "I trade perfect for finished.",
  "I keep going on the days it doesn't feel like progress.",
  "Attention today is a gift to the week.",
  "I let the small win count.",
  "I make the plan simple enough to actually do.",
  "I choose what to be bad at.",
  "My calendar tells the truth about my priorities.",
  "I take the walk. It counts as work.",
  "I begin again as many times as it takes.",
  "The quiet days are the ones that build it.",
  "I do this for the person I'm becoming.",
];
